# Generated by Django 4.2.20 on 2025-04-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='fakultas',
            field=models.CharField(choices=[('FH', 'Fakultas Hukum'), ('FEB', 'Fakultas Ekonomi dan Bisnis'), ('FK', 'Fakultas Kedokteran'), ('FKG', 'Fakultas Kedokteran Gigi'), ('FTSP', 'Fakultas Teknik Sipil dan Perencanaan'), ('FTI', 'Fakultas Teknologi Industri'), ('FTKE', 'Fakultas Teknologi Kebumian dan Energi'), ('FALTL', 'Fakultas Arsitektur Lanskap dan Teknologi Lingkungan'), ('FSRD', 'Fakultas Seni Rupa dan Desain')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(choices=[('TI', 'Teknik Informatika'), ('SI', 'Sistem Informasi'), ('TE', 'Teknik Elektro'), ('TM', 'Teknik Mesin'), ('TInd', 'Teknik Industri'), ('TS', 'Teknik Sipil'), ('Ars', 'Arsitektur'), ('PWK', 'Perencanaan Wilayah dan Kota'), ('TG', 'Teknik Geologi'), ('TPM', 'Teknik Perminyakan'), ('TPT', 'Teknik Pertambangan'), ('DI', 'Desain Interior'), ('DP', 'Desain Produk'), ('DKV', 'Desain Komunikasi Visual'), ('AL', 'Arsitektur Lanskap'), ('TL', 'Teknik Lingkungan'), ('Man', 'Manajemen'), ('Ak', 'Akuntansi'), ('EP', 'Ekonomi Pembangunan'), ('Hukum', 'Ilmu Hukum'), ('Kedokteran', 'Pendidikan Dokter'), ('KedokteranGigi', 'Pendidikan Dokter Gigi')], max_length=14),
        ),
    ]
